name: MinigamePlugin
main: minigames.main.Main
authors: [Lucas_gamer13, Gabriel8579]
version: 1.0
commands:
  mundo:
    description: Crie, liste e edite mundos.
  sala:
    description: Entre em uma sala ou veja em qual sala voce esta.
  adm:
    description: Comando para administradores.
  admgame:
    description: Comando para administradores.